import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { DefaultQueryCell } from "../utils/DefaultQueryCell";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const lastClickedQuery = trpc.useQuery(["button.lastClicked"]);
  console.log("🚀 ~ file: index.tsx ~ line 17 ~ lastClicked", lastClickedQuery);

  const [input, setInput] = useState("");

  const onClickOfButton = trpc.useMutation(["button.clicked"]);

  return (
    <>
      <Head>
        <title>The Button</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <input
          type={"text"}
          onChange={(e) => setInput(e.target.value)}
          value={input}
        ></input>
        <DefaultQueryCell
          query={lastClickedQuery}
          success={({ data }) => (
            <>
              <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
                Last time this button was clicked by{" "}
                <span className="text-purple-300">{data?.name}</span>
              </h1>
            </>
          )}
          empty={() => <p>Err.. there is meant to be data here</p>}
        />
        <div className="flex space-x-2 justify-center">
          <button
            onClick={() => onClickOfButton.mutate({ name: input })}
            type="button"
            className="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"
          >
            Button
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
