import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
import SignIn from "../components/SignIn";
import { DefaultQueryCell } from "../utils/DefaultQueryCell";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const lastClickedQuery = trpc.useQuery(["button.lastClicked"]);
  const buttonClickedMutation = trpc.useMutation(["button.clicked"]);

  return (
    <>
      <Head>
        <title>The Button</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignIn />
      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <DefaultQueryCell
          query={lastClickedQuery}
          success={({ data }) => {
            return (
              <>
                <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
                  The last person to click was{" "}
                  <span className="text-purple-300">{data?.id}</span>
                  {" on "}
                  <span className="text-blue-300">
                    {data?.createdAt.toLocaleString()}
                  </span>
                </h1>
                <div className="flex space-x-2 justify-center">
                  <Button onClick={() => buttonClickedMutation.mutate()}>
                    Button
                  </Button>
                </div>
              </>
            );
          }}
          empty={() => (
            <>
              <p>Err.. there is meant to be data here</p>{" "}
              <Button onClick={() => buttonClickedMutation.mutate()}>
                Button
              </Button>
            </>
          )}
        />
      </main>
    </>
  );
};

export default Home;
